version: '3.7'

services:
  sicepat_app:
    container_name: sicepat_app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3010:3010
    command: npm run start:dev
    # Comment this line for easy changing ENV from .env file
    # env_file:
      # - .env
    networks:
      - sicepatnet
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: sicepat_postgres
    image: postgres:12-alpine
    networks:
      - sicepatnet
    ports:
      - "5432:5432"
    volumes:
      - db-data:/data/postgres
      # - ./_data/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env

  redis:
    container_name: sicepat_redis
    image: redis:5
    networks:
      - sicepatnet
    ports:
      - 6379:6379

networks:
  sicepatnet:
    name: sicepatnet

volumes:
  db-data:
